"""Made adjustments to the price column

Revision ID: 076b02e40e5d
Revises: bc6e822dfecf
Create Date: 2023-04-26 08:36:08.878677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '076b02e40e5d'
down_revision = 'bc6e822dfecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=4, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
